---
abstract: 'Perl client for the Easypost.co service'
author:
  - 'Mark Allen <mrallen1@yahoo.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Easypost
requires:
  Hash::Merge::Simple: 0.051
  Mojo: 3.62
  Moo: 1.000006
  perl: 5.014
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Easypost
  homepage: https://metacpan.org/dist/Net-Easypost
  repository: git://github.com/mrallen1/Net-Easypost.git
version: 0.02
