---
abstract: 'Perl client for the Easypost web service'
author:
  - 'Mark Allen <mrallen1@yahoo.com>, Hunter McMillen <mcmillhj@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Easypost
requires:
  Hash::Merge::Simple: 0.051
  IO::Socket::SSL: 1.962
  Mojolicious: 4.66
  Moo: 1.004002
  perl: 5.016
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Easypost
  homepage: https://metacpan.org/dist/Net-Easypost
  repository: git://github.com/mrallen1/Net-Easypost.git
version: 0.10
